### ISSUE TITLE
storing objects

### ISSUE THREAD

**Issue by joques** [elbart/node-memcache#20]
Hi,
this is more of a question. I am using the memcache module to cache some objects from a riak database. Suppose I have a simple object {me: "one", you: "two"} associated with a key abc123. And I'd like to store this object in the cache. So I do client.set('abc123', {me: "one", you: "two"}, (error, val)... Later, when I tried to fetch the object from the cache, I get [object, Object]. Was I not supposed to store the object directly in the cache? Have I missed something?

**Comment by elbart** [comment]
We currently only support strings to be stored.

Instead of passing the object you should serialize it to a string before. Just use JSON.stringify(obj). And after retrieval you can use obj = JSON.parse(cacheResult) to get an object again.

Otherwise you could also extend this project with the needed function but my time doesn't allow me to do that right now properly.

**Comment by joques** [comment]
thanks for your quick response. It works
